# Cloudflare Workers configuration for AmbientFlow PWA
name = "ambient-flow"
main = "worker/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment configuration
[env.preview]
name = "ambient-flow-preview"

# Assets configuration for static files
[assets]
directory = "./dist"

# KV namespaces for caching and data storage
[[kv_namespaces]]
binding = "CACHE_KV"
id = "d3220f4c6b2f4bceadf84f83e49a639a"
preview_id = "2f10842d479b429da3469083fee2871d"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "5de8b6faf9ad4f3f80dc954b524dd71b"
preview_id = "7d696c344aa7418b95aad55e0651a866"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "AmbientFlow"
APP_VERSION = "1.0.0"
API_BASE_URL = "https://ambient-flow.kshiva1126.workers.dev"

# Development configuration
[env.development]
name = "ambient-flow-dev"
[env.development.vars]
ENVIRONMENT = "development"
APP_NAME = "AmbientFlow Dev"

# Note: Build is handled by GitHub Actions

# Limits and optimization (removed for Free plan compatibility)
# [limits]
# cpu_ms = 50

# Triggers
[triggers]
crons = ["0 0 * * *"]  # Daily cleanup at midnight